import 'package:superwallkit_flutter/src/generated/superwallhost.g.dart';
import 'package:superwallkit_flutter/superwallkit_flutter.dart';

/// The delegate protocol that handles Superwall lifecycle events.
///
/// The delegate methods receive callbacks from the SDK in response to certain placements.
///
/// You set this directly using ``Superwall/delegate``.
///
/// To learn how to conform to the delegate in your app and best practices, see
/// [our docs](https://docs.superwall.com/docs/3rd-party-analytics).
abstract class SuperwallDelegate {
  /// Called when the property `subscriptionStatus` of `Superwall` changes.
  void subscriptionStatusDidChange(SubscriptionStatus newValue);

  /// Called whenever an internal analytics placement is tracked.
  void handleSuperwallEvent(SuperwallEventInfo eventInfo);

  /// Called when the user taps an element on your paywall with a custom action.
  void handleCustomPaywallAction(String name);

  /// Called right before the paywall is dismissed.
  void willDismissPaywall(PaywallInfo paywallInfo);

  /// Called right before the paywall is presented.
  void willPresentPaywall(PaywallInfo paywallInfo);

  /// Called right after the paywall is dismissed.
  void didDismissPaywall(PaywallInfo paywallInfo);

  /// Called right after the paywall is presented.
  void didPresentPaywall(PaywallInfo paywallInfo);

  /// Called when the user opens a URL with a specific tag on your paywall.
  void paywallWillOpenURL(Uri url);

  /// Called when the user taps a deep link in your paywall.
  void paywallWillOpenDeepLink(Uri url);

  /// Receive all log messages generated by the SDK.
  void handleLog(String level, String scope, String? message,
      Map<dynamic, dynamic>? info, String? error);

  /// Called before the redemption of a code from a web paywall.
  void willRedeemLink() => {};

  /// A code was redeemed from a web paywall.
  void didRedeemLink(RedemptionResult result) => {};

  /// Called after handling a Superwall deep link with the format
  /// `yoursubdomain.superwall.app/app-link/...`.
  void handleSuperwallDeepLink(Uri fullURL, List<String> pathComponents,
      Map<String, String> queryParameters);
}

class SuperwallDelegateHost implements PSuperwallDelegateGenerated {
  final SuperwallDelegate _delegate;

  SuperwallDelegateHost(this._delegate);

  @override
  void subscriptionStatusDidChange(
      PSubscriptionStatus from, PSubscriptionStatus to) async {
    final status =
        SubscriptionStatus.createSubscriptionStatusFromPSubscriptionStatus(to);
    _delegate.subscriptionStatusDidChange(status);
  }

  @override
  void handleSuperwallEvent(PSuperwallEventInfo eventInfo) {
    final info = SuperwallEventInfo.fromPEventInfo(eventInfo);
    _delegate.handleSuperwallEvent(info);
  }

  @override
  void handleCustomPaywallAction(String name) {
    _delegate.handleCustomPaywallAction(name);
  }

  @override
  void willDismissPaywall(PPaywallInfo paywallInfo) {
    final info = PaywallInfo.fromPigeon(paywallInfo);
    if (info != null) {
      _delegate.willDismissPaywall(info);
    }
  }

  @override
  void willPresentPaywall(PPaywallInfo paywallInfo) {
    final info = PaywallInfo.fromPigeon(paywallInfo);
    if (info != null) {
      _delegate.willPresentPaywall(info);
    }
  }

  @override
  void didDismissPaywall(PPaywallInfo paywallInfo) {
    final info = PaywallInfo.fromPigeon(paywallInfo);
    if (info != null) {
      _delegate.didDismissPaywall(info);
    }
  }

  @override
  void didPresentPaywall(PPaywallInfo paywallInfo) {
    final info = PaywallInfo.fromPigeon(paywallInfo);
    if (info != null) {
      _delegate.didPresentPaywall(info);
    }
  }

  @override
  void paywallWillOpenURL(String url) {
    try {
      final uri = Uri.parse(url);
      _delegate.paywallWillOpenURL(uri);
    } catch (e) {
      // Error parsing URL
    }
  }

  @override
  void paywallWillOpenDeepLink(String url) {
    try {
      final uri = Uri.parse(url);
      _delegate.paywallWillOpenDeepLink(uri);
    } catch (e) {
      // Error parsing deep link URL
    }
  }

  @override
  void handleLog(String level, String scope, String? message,
      Map<String, Object>? info, String? error) {
    _delegate.handleLog(level, scope, message, info, error);
  }

  @override
  void willRedeemLink() {
    _delegate.willRedeemLink();
  }

  @override
  void didRedeemLink(PRedemptionResult result) {
    try {
      final type = RedemptionResult.fromPigeon(result);
      _delegate.didRedeemLink(type);
    } catch (e) {
      // Error parsing RedemptionResult
    }
  }

  @override
  void handleSuperwallDeepLink(String fullURL, List<String> pathComponents,
      Map<String, String> queryParameters) {
    try {
      final uri = Uri.parse(fullURL);
      _delegate.handleSuperwallDeepLink(uri, pathComponents, queryParameters);
    } catch (e) {
      // Error parsing URL
    }
  }
}
